name: commitlint-preset
on:
  push:
    paths:
      - '.github/workflows/commitlint-preset.yml'
      - 'commitlint-preset/**'
jobs:
  job:
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        working-directory: commitlint-preset
        run: npm ci
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: commitlint-preset
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
