name: semantic-release-config
on:
  push:
    paths:
      - '.github/workflows/semantic-release-config.yml'
      - 'semantic-release-config/**'
jobs:
  job:
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        working-directory: semantic-release-config
        run: npm ci
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: semantic-release-config
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
