name: semantic-release-config
on:
  push:
    paths:
      - '.github/workflows/semantic-release-config.yml'
      - 'semantic-release-config/**'
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js Active LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: 'semantic-release-config/package-lock.json'
      - name: Prepare
        working-directory: semantic-release-config
        run: npm ci
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: semantic-release-config
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
